## These two functions work together to calculate and store the inverse of a matrix. 

## makeCacheMatrix receives an invertible matrix and creates an object
## that stores the matrix value and the inverse matrix when called via cacheSolve

makeCacheMatrix <- function(x = matrix()) {
        m<-NULL
        get<- function () x
        setInv<- function(inv) m<<-inv
        getInv<- function () m
        list(get = get, setInv = setInv, getInv = getInv)
        

}


## cacheSolve receives the object generated by makeCacheMatrix. If there is a stored
## inverse matrix, cacheSolve retrieves that value. If there is no stored inverse,
## cacheSolve retrieves the matrix data from the object and calculates the inverse. 
## This value is then stored in the original object.

cacheSolve <- function(x, ...) {
      m<-x$getInv()
      if(!is.null(m)){
              message("retrieving cached data")
              return(m)
      }
      data<-x$get()
      m<-solve(data)
      x$setInv(m)
      m
}
